### ISSUE TITLE
Homebridge Hue Connect Problem

### ISSUE THREAD

**Issue by Schmello** [marthoc/docker-deconz#349]
I installed the Homebridge Hue plugin and entered the IP and port.
In deconz I activated Connect App and then restarted the Homebridge Server.
The Homebridge Protocol says the following. This repeats itself over and over again.
No username and password will be created.

```
[1/29/2021, 5:23:08 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:23:29 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:23:49 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:23:49 PM] [Hue] Phoscon-GW: TypeError: Cannot read property 'config' of undefined
    at HueBridge.exposeBridge (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:188:56)
    at HueBridge.accessories (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:113:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:352:29) - retrying in 15s
[1/29/2021, 5:24:04 PM] [Hue] Phoscon-GW: RaspBee/ConBee not yet initialised - wait 1 minute
[1/29/2021, 5:24:09 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:24:29 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:24:49 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:25:04 PM] [Hue] Phoscon-GW: TypeError: Cannot read property 'config' of undefined
    at HueBridge.exposeBridge (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:188:56)
    at HueBridge.accessories (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:113:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:352:29) - retrying in 15s
[1/29/2021, 5:25:09 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:25:19 PM] [Hue] Phoscon-GW: RaspBee/ConBee not yet initialised - wait 1 minute
[1/29/2021, 5:25:29 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:25:49 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
```

In the iobroker the generation of the api key works without problems.

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. You should either ask your question in the homebridge hue repo or in the Deconz repo.

Closing.
